# Generated by Django 5.2 on 2025-04-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_recieived',
            new_name='order_received',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='oredered',
            new_name='ordered',
        ),
    ]
