# Generated by Django 5.2 on 2025-04-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkoutaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='appartment_address',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
